import { env } from 'cloudflare:workers';
import { ZodError } from 'zod';
import { GameError,createGame,applyAction,total,type Game } from '../game/engine';
import { createSchema,actionSchema,saveSchema } from '../game/contracts';
function db(){if(!env.DB)throw new Error('Missing DB');return env.DB;}
export function owner(req:Request){const user=req.headers.get('oai-authenticated-user-id');return user || 'guest-local-user';}
function checkOrigin(req:Request){if(req.method==='GET')return;const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new GameError('Solicitud no permitida.','FORBIDDEN',403);}
export function endpoint(fn:(req:Request)=>Promise<unknown>){return async(req:Request)=>{try{checkOrigin(req);const result=await fn(req);return Response.json({data:result},{headers:{'Cache-Control':'no-store'}});}catch(e){if(e instanceof ZodError)return Response.json({error:{code:'VALIDATION',message:'Revisa los datos enviados.'}},{status:400});if(e instanceof SyntaxError)return Response.json({error:{code:'VALIDATION',message:'La solicitud no es válida.'}},{status:400});if(e instanceof GameError)return Response.json({error:{code:e.code,message:e.message}},{status:e.status});console.error('Cacho request failed',e);return Response.json({error:{code:'INTERNAL',message:'No pudimos completar la operación. Inténtalo de nuevo.'}},{status:500});}};}
function secureDie(){const max=4294967292;let n;do{n=crypto.getRandomValues(new Uint32Array(1))[0];}while(n>=max);return n%6+1;}
async function row(id:string,user:string){const r=await db().prepare('SELECT state, version, last_action FROM games WHERE id = ? AND owner = ?').bind(id,user).first<{state:string;version:number;last_action:string|null}>();if(!r)throw new GameError('No encontramos esta partida.','NOT_FOUND',404);return r;}
export async function getGame(id:string,user:string){return JSON.parse((await row(id,user)).state) as Game;}
export async function create(req:Request){const user=owner(req),p=createSchema.parse(await req.json()),g=createGame(crypto.randomUUID(),p.names,p.mode,p.opponent,p.avatars);await db().prepare('INSERT INTO games (id, owner, state, version, status, updated_at) VALUES (?, ?, ?, ?, ?, ?)').bind(g.id,user,JSON.stringify(g),g.version,g.status,g.updatedAt).run();return g;}
export async function listGames(req:Request){const user=owner(req);const r=await db().prepare("SELECT state FROM games WHERE owner = ? AND status = 'playing' ORDER BY updated_at DESC LIMIT 1").bind(user).all<{state:string}>();return r.results.map(r=>JSON.parse(r.state) as Game);}
export async function act(req:Request,id:string){const user=owner(req),p=actionSchema.parse(await req.json()),r=await row(id,user);if(r.last_action===p.actionId)return JSON.parse(r.state);if(r.version!==p.expectedVersion)throw new GameError('La partida cambió. Actualiza para continuar.','CONFLICT',409);const g=applyAction(JSON.parse(r.state),p.action,secureDie);const result=await db().prepare('UPDATE games SET state = ?, version = ?, last_action = ?, status = ?, updated_at = ? WHERE id = ? AND owner = ? AND version = ?').bind(JSON.stringify(g),g.version,p.actionId,g.status,g.updatedAt,id,user,p.expectedVersion).run();if(!result.meta.changes){const updated=await row(id,user);if(updated.last_action===p.actionId)return JSON.parse(updated.state);throw new GameError('Otra acción ya actualizó la partida.','CONFLICT',409);}return g;}
export async function save(req:Request){const user=owner(req),p=saveSchema.parse(await req.json()),g=await getGame(p.gameId,user);if(g.version!==p.expectedVersion)throw new GameError('Actualiza la partida antes de guardarla.','CONFLICT',409);const id=crypto.randomUUID();await db().prepare('INSERT INTO saves (id, owner, game_id, name, state, created_at) VALUES (?, ?, ?, ?, ?, ?)').bind(id,user,g.id,p.name,JSON.stringify(g),new Date().toISOString()).run();return {id};}
export async function listSaves(req:Request){const r=await db().prepare('SELECT id, name, state, created_at FROM saves WHERE owner = ? ORDER BY created_at DESC LIMIT 100').bind(owner(req)).all<{id:string;name:string;state:string;created_at:string}>();return r.results.map(r=>({id:r.id,name:r.name,createdAt:r.created_at,game:JSON.parse(r.state) as Game}));}
export async function removeSave(req:Request,id:string){const r=await db().prepare('DELETE FROM saves WHERE id = ? AND owner = ?').bind(id,owner(req)).run();if(!r.meta.changes)throw new GameError('Guardado no encontrado.','NOT_FOUND',404);return {deleted:true};}
export async function restore(req:Request,id:string){const user=owner(req);const r=await db().prepare('SELECT state FROM saves WHERE id = ? AND owner = ?').bind(id,user).first<{state:string}>();if(!r)throw new GameError('Guardado no encontrado.','NOT_FOUND',404);const g=JSON.parse(r.state) as Game;const original=await row(g.id,user);if((JSON.parse(original.state) as Game).status==='finished')return JSON.parse(original.state);g.version=original.version+1;g.updatedAt=new Date().toISOString();g.lastEvent='Partida recuperada. ¡Seguimos jugando!';const result=await db().prepare('UPDATE games SET state = ?, version = ?, last_action = NULL, status = ?, updated_at = ? WHERE id = ? AND owner = ? AND version = ?').bind(JSON.stringify(g),g.version,g.status,g.updatedAt,g.id,user,original.version).run();if(!result.meta.changes)throw new GameError('La partida cambió mientras se recuperaba.','CONFLICT',409);return g;}
export async function ranking(req:Request){const r=await db().prepare("SELECT state FROM games WHERE owner = ? AND status = 'finished' ORDER BY updated_at DESC LIMIT 200").bind(owner(req)).all<{state:string}>();return r.results.flatMap(r=>{const g=JSON.parse(r.state) as Game;const high=Math.max(...g.players.map(total));return g.players.filter(p=>total(p)===high).map(p=>({id:g.id+'-'+p.name,name:p.name,avatar:p.avatar,points:total(p),date:g.updatedAt,mode:g.mode,tie:total(g.players[0])===total(g.players[1])}));}).sort((a,b)=>b.points-a.points).slice(0,50);}
